spring:
  cloud:
    gateway:
      enabled: false
      routes:
        - id: google-route
          uri: https://www.google.com
          predicates:
            - Path=/red/{segment}
            - Method=GET
          filters:
            - AddRequestHeader=X-Request-red, blue


gateway-app:
  enabled: true
  hosts:
    - id: google-gateway
      uri: https://google.com
    - id: microsoft-host
      uri: https://www.microsoft.com
    - id: dummy-json
      uri: https://dummyjson.com
    - id: local-server
      uri: http://localhost:5000
  routes:
    - id: dummy-json-products-list
      host-id: dummy-json
      predicates:
        - Path=/products
        - RequestMethod=GET,POST
      upstream:
        contextPath: /products
        method: GET
    - id: microsoft-website-query
      host-id: microsoft-host
      predicates:
        - Path=/path-by-query
        - Query=site,microsoft
      upstream:
        contextPath: /products
        method: GET
    - id: google-website-query
      host-id: google-gateway
      predicates:
        - Path=/path-by-query
        - Query=site,google
      upstream:
        contextPath: /products
        method: GET
    - id: google-website
      host-id: google-gateway
      predicates:
        - Path=/**
      upstream:
        method: GET


logging:
  level:
    com.priyanshu.springwebfluxbffapp: debug